Add Code to Cloud Spec
ballerina-platform/ballerina-spec pull request #605
Opened 2020-09-25 03:40 UTC by xlight05

## Purpose
> Contains Code to Cloud Specification.

2020-09-25 03:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/ballerina-spec?pullRequest=605) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/ballerina-spec?pullRequest=605) before we can accept your contribution.<br/><hr/>**Anjana Supun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/ballerina-spec?pullRequest=605) it.</sub>

2020-10-02 05:31 UTC, anuruddhal requested changes

2020-10-02 05:31 UTC, anuruddhal commented on c2c/code-to-cloud-spec.md
> +[cloud.config]
Let's add the new syntax:
```
[[cloud.config.envs]]
name= "b7a_log_level"
config_name= "cm-loglevel-linker"
key= "B7A_LOG_LEVEL"

[[cloud.config.envs]]
name= "IDP_ISSUER"
config_name= "cm-idp"
key= "IDP_ISSUER"
```

2020-10-12 05:52 UTC, afkham requested changes
Tables should be in markdown syntax not HTML

2020-10-13 04:38 UTC, afkham approved these changes

2020-10-13 04:38 UTC, merged