Add spec conformance tests for xml-template-expr
ballerina-platform/ballerina-spec pull request #951
Opened 2021-10-05 14:06 UTC by gimantha

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/32635

2021-10-06 08:31 UTC, lochana-chathura commented on conformance/lang/expressions/xml-template-expr.balt
> +import ballerina/io;
No need add `import ballerina/io;` here and other places

2021-10-06 08:31 UTC, lochana-chathura commented on conformance/lang/expressions/xml-template-expr.balt
> +    xml<xml:Text> x4 = xml `text${()}`; // @error int? type not allowed in xml text
```suggestion
    xml<xml:Text> _ = xml `text${firstExpr}`; // @error int? type not allowed in xml text
    xml<xml:Text> _ = xml `text${()}`; // @error int? type not allowed in xml text
```

Need to use wildcard-bindin-pattern for unused variables.

2021-10-06 08:31 UTC, lochana-chathura commented on conformance/lang/expressions/xml-template-expr.balt
> +Labels: xml-template-expr, xml, raw-template-expr, nil-type
Missing labels union-type, float, decimal etc in here and other places.

2021-12-06 16:19 UTC, hasithaa commented
The Team is busy with finalizing the SwanLake GA release. Hence closing this PR temporarily.

2022-06-02 11:16 UTC, suleka96 requested changes

2022-06-02 11:16 UTC, suleka96 commented on conformance/lang/expressions/xml_template_expr.balt
> +Labels: xml-template-expr, xml, member-access-expr
Shall we add the missing labels here and please check other places in the file as well, there seems to be quite a bit that has been missed.

2022-06-02 11:16 UTC, suleka96 commented on conformance/lang/expressions/xml_template_expr.balt
> +Labels: xml-template-expr, xml, optional-field-access-expr
Missing label `record-type`

2022-06-02 11:16 UTC, suleka96 commented on conformance/lang/expressions/xml_template_expr.balt
> +Labels: xml-template-expr, xml, query-expr
`query-expr` label is missing

2022-06-02 11:16 UTC, suleka96 commented on conformance/lang/expressions/xml_template_expr.balt
> +}
Have we added tests for 

> An xml-template-expr occurring within a const-expr will construct an xml value that has its read-only bit on.

2022-06-03 06:11 UTC, chiranSachintha commented on conformance/lang/expressions/xml_template_expr.balt
> +Labels: xml-template-expr, xml, optional-field-access-expr
`module-type-defn` as well.

2022-06-03 06:11 UTC, chiranSachintha commented on conformance/lang/expressions/xml_template_expr.balt
> +Test-Case: output
Shall we add a few tests with type-cast-expr?

2022-06-03 06:11 UTC, chiranSachintha commented on conformance/lang/expressions/xml_template_expr.balt
> +public function init() {
`init` function cannot be public. Need to change every other places

2024-07-15 06:15 UTC, closed without merging